# Classification Exercise

We'll be working with some California Census Data, we'll be trying to use various features of an individual to predict what class of income they belogn in (>50k or <=50k). 

Here is some information about the data:

<table>
<thead>
<tr>
<th>Column Name</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>age</td>
<td>Continuous</td>
<td>The age of the individual</td>
</tr>
<tr>
<td>workclass</td>
<td>Categorical</td>
<td>The type of employer the  individual has (government,  military, private, etc.).</td>
</tr>
<tr>
<td>fnlwgt</td>
<td>Continuous</td>
<td>The number of people the census  takers believe that observation  represents (sample weight). This  variable will not be used.</td>
</tr>
<tr>
<td>education</td>
<td>Categorical</td>
<td>The highest level of education  achieved for that individual.</td>
</tr>
<tr>
<td>education_num</td>
<td>Continuous</td>
<td>The highest level of education in  numerical form.</td>
</tr>
<tr>
<td>marital_status</td>
<td>Categorical</td>
<td>Marital status of the individual.</td>
</tr>
<tr>
<td>occupation</td>
<td>Categorical</td>
<td>The occupation of the individual.</td>
</tr>
<tr>
<td>relationship</td>
<td>Categorical</td>
<td>Wife, Own-child, Husband,  Not-in-family, Other-relative,  Unmarried.</td>
</tr>
<tr>
<td>race</td>
<td>Categorical</td>
<td>White, Asian-Pac-Islander,  Amer-Indian-Eskimo, Other, Black.</td>
</tr>
<tr>
<td>gender</td>
<td>Categorical</td>
<td>Female, Male.</td>
</tr>
<tr>
<td>capital_gain</td>
<td>Continuous</td>
<td>Capital gains recorded.</td>
</tr>
<tr>
<td>capital_loss</td>
<td>Continuous</td>
<td>Capital Losses recorded.</td>
</tr>
<tr>
<td>hours_per_week</td>
<td>Continuous</td>
<td>Hours worked per week.</td>
</tr>
<tr>
<td>native_country</td>
<td>Categorical</td>
<td>Country of origin of the  individual.</td>
</tr>
<tr>
<td>income</td>
<td>Categorical</td>
<td>"&gt;50K" or "&lt;=50K", meaning  whether the person makes more  than \$50,000 annually.</td>
</tr>
</tbody>
</table>

## Follow the Directions in Bold. If you get stuck, check out the solutions lecture.

### THE DATA

** Read in the census_data.csv data with pandas**

In [1]:
import pandas as pd

In [2]:
census = pd.read_csv('Data/census_data.csv')

In [3]:
census

,age,workclass,education,education_num,marital_status,occupation,relationship,race,gender,capital_gain,capital_loss,hours_per_week,native_country,income_bracket
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

** TensorFlow won't be able to understand strings as labels, you'll need to use pandas .apply() method to apply a custom function that converts them to 0s and 1s. This might be hard if you aren't very familiar with pandas, so feel free to take a peek at the solutions for this part.**

** Convert the Label column to 0s and 1s instead of strings.**

In [4]:
census['income_bracket'].unique()

array([' <=50K', ' >50K'], dtype=object)

In [5]:
def label_fix(label):
    if label == ' <=50K':
        return 0
    else:
        return 1

In [6]:
census['income_bracket'] = census['income_bracket'].apply(label_fix)

In [7]:
census

,age,workclass,education,education_num,marital_status,occupation,relationship,race,gender,capital_gain,capital_loss,hours_per_week,native_country,income_bracket
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,0
32557,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,1
32558,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,0
32559,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,0
32560,52,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,1

### Perform a Train Test Split on the Data

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_data = census.drop(['income_bracket'], axis=1)

In [10]:
y_label = census['income_bracket']

In [11]:
x_train, x_test, y_train, y_test = train_test_split(
    x_data, y_label, test_size=0.3, random_state=101)

### Create the Feature Columns for tf.esitmator

** Take note of categorical vs continuous values! **

In [12]:
census.columns

Index(['age', 'workclass', 'education', 'education_num', 'marital_status',
       'occupation', 'relationship', 'race', 'gender', 'capital_gain',
       'capital_loss', 'hours_per_week', 'native_country', 'income_bracket'],
      dtype='object')

** Import Tensorflow **

In [13]:
import tensorflow as tf

** Create the tf.feature_columns for the categorical values. Use vocabulary lists or just use hash buckets. **

In [14]:
gender = tf.feature_column.categorical_column_with_hash_bucket("gender", 1000)
occupation = tf.feature_column.categorical_column_with_hash_bucket("occupation", 1000)
marital_status = tf.feature_column.categorical_column_with_hash_bucket("marital_status", 1000)
relationship = tf.feature_column.categorical_column_with_hash_bucket("relationship", 1000)
education = tf.feature_column.categorical_column_with_hash_bucket("education", 1000)
workclass = tf.feature_column.categorical_column_with_hash_bucket("workclass", 1000)
native_country = tf.feature_column.categorical_column_with_hash_bucket("native_country", 1000)
race = tf.feature_column.categorical_column_with_hash_bucket("race", 1000)

** Create the continuous feature_columns for the continuous values using numeric_column **

In [15]:
age = tf.feature_column.numeric_column("age")
education_num = tf.feature_column.numeric_column("education_num")
capital_gain = tf.feature_column.numeric_column("capital_gain")
capital_loss = tf.feature_column.numeric_column("capital_loss")
hours_per_week = tf.feature_column.numeric_column("hours_per_week")

** Put all these variables into a single list with the variable name feat_cols **

In [16]:
feat_cols = [gender, occupation, marital_status, relationship, education, workclass, native_country, race, age, education_num, capital_gain, capital_loss, hours_per_week]

### Create Input Function

** Batch_size is up to you. But do make sure to shuffle!**

In [17]:
input_func = tf.estimator.inputs.pandas_input_fn(x=x_train, y=y_train, batch_size=100, num_epochs=None, shuffle=True)

#### Create your model with tf.estimator

**Create a LinearClassifier.(If you want to use a DNNClassifier, keep in mind you'll need to create embedded columns out of the cateogrical feature that use strings, check out the previous lecture on this for more info.)**

In [18]:
model = tf.estimator.LinearClassifier(feature_columns=feat_cols)

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: C:\Users\Hasal\AppData\Local\Temp\tmpheb616br
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\Hasal\\AppData\\Local\\Temp\\tmpheb616br', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000029259293188>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}

** Train your model on the data, for at least 5000 steps. **

In [19]:
model.train(input_fn=input_func, steps=10000)

WARNING:tensorflow:From C:\Users\Hasal\Anaconda3\lib\site-packages\tensorflow\python\training\training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
WARNING:tensorflow:From C:\Users\Hasal\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\inputs\queues\feeding_queue_runner.py:62: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From C:\Users\Hasal\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\inputs\queues\feeding_functions.py:500: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:Entity <bound method LinearModel.call of <tensorflow.python.feature_column.feature_column_v2.LinearModel object at 0x000002925A49E708>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method LinearModel.call of <tensorflow.python.feature_column.feature_column_v2.LinearModel object at 0x000002925A49E708>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING: Entity <bound method LinearModel.call of <tensorflow.python.feature_column.feature_column_v2.LinearModel object at 0x000002925A49E708>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method LinearModel.call of <tensorflow.python.feature_column.feature_column_v2.LinearModel object at 0x000002925A49E708>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method _LinearModelLayer.call of <tensorflow.python.feature_column.feature_column_v2._LinearModelLayer object at 0x000002925A49ED88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _LinearModelLayer.call of <tensorflow.python.feature_column.feature_column_v2._LinearModelLayer object at 0x000002925A49ED88>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING: Entity <bound method _LinearModelLayer.call of <tensorflow.python.feature_column.feature_column_v2._LinearModelLayer object at 0x000002925A49ED88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _LinearModelLayer.call of <tensorflow.python.feature_column.feature_column_v2._LinearModelLayer object at 0x000002925A49ED88>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:From C:\Users\Hasal\Anaconda3\lib\site-packages\tensorflow\python\feature_column\feature_column_v2.py:2655: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From C:\Users\Hasal\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\canned\linear.py:308: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
WARNING:tensorflow:From C:\Users\Hasal\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py:875: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\Hasal\AppData\Local\Temp\tmpheb616br\model.ckpt.
INFO:tensorflow:loss = 69.31474, step = 1
INFO:tensorflow:global_step/sec: 114.481
INFO:tensorflow:loss = 83.65095, step = 101 (0.875 sec)
INFO:tensorflow:global_step/sec: 393.969
INFO:tensorflow:loss = 179.63803, step = 201 (0.254 sec)
INFO:tensorflow:global_step/sec: 189.828
INFO:tensorflow:loss = 173.45221, step = 301 (0.527 sec)
INFO:tensorflow:global_step/sec: 330.259
INFO:tensorflow:loss = 78.631775, step = 401 (0.304 sec)
INFO:tensorflow:global_step/sec: 260.859
INFO:tensorflow:loss = 362.48593, step = 501 (0.385 sec)
INFO:tensorflow:global_step/sec: 206.18
INFO:tensorflow:loss = 172.77144, step = 601 (0.482 sec)
INFO:tensorflow:global_step/sec: 262.096
INFO:tensorflow:loss = 142.65369, step = 701 (0.381 sec)
INFO:tensorflow:global_step/sec: 394.753
INFO:tensorflow:loss = 34.290665, step = 801 (0.254 sec)
INFO:tensorflow:global_step/sec: 343.35
INFO:tensorflow:loss = 785.5644, step = 901 (0.295 sec)
INFO:tensorflow:global_step/sec: 356.186
INFO:tensorflow:loss = 38.807285, step = 1001 (0.278 sec)
INFO:tensorflow:global_step/sec: 334.225
INFO:tensorflow:loss = 19.91626, step = 1101 (0.298 sec)
INFO:tensorflow:global_step/sec: 256.438
INFO:tensorflow:loss = 346.5171, step = 1201 (0.390 sec)
INFO:tensorflow:global_step/sec: 308.357
INFO:tensorflow:loss = 96.95863, step = 1301 (0.327 sec)
INFO:tensorflow:global_step/sec: 364.54
INFO:tensorflow:loss = 34.524757, step = 1401 (0.273 sec)
INFO:tensorflow:global_step/sec: 401.786
INFO:tensorflow:loss = 146.9025, step = 1501 (0.247 sec)
INFO:tensorflow:global_step/sec: 407.587
INFO:tensorflow:loss = 46.34707, step = 1601 (0.245 sec)
INFO:tensorflow:global_step/sec: 360.679
INFO:tensorflow:loss = 105.378525, step = 1701 (0.277 sec)
INFO:tensorflow:global_step/sec: 309.463
INFO:tensorflow:loss = 272.82617, step = 1801 (0.325 sec)
INFO:tensorflow:global_step/sec: 393.848
INFO:tensorflow:loss = 208.83914, step = 1901 (0.252 sec)
INFO:tensorflow:global_step/sec: 320.657
INFO:tensorflow:loss = 161.88718, step = 2001 (0.318 sec)
INFO:tensorflow:global_step/sec: 301.567
INFO:tensorflow:loss = 96.629745, step = 2101 (0.326 sec)
INFO:tensorflow:global_step/sec: 348.158
INFO:tensorflow:loss = 43.290882, step = 2201 (0.287 sec)
INFO:tensorflow:global_step/sec: 371.359
INFO:tensorflow:loss = 110.094955, step = 2301 (0.270 sec)
INFO:tensorflow:global_step/sec: 374.104
INFO:tensorflow:loss = 212.05092, step = 2401 (0.267 sec)
INFO:tensorflow:global_step/sec: 335.205
INFO:tensorflow:loss = 39.225693, step = 2501 (0.304 sec)
INFO:tensorflow:global_step/sec: 296.285
INFO:tensorflow:loss = 235.69028, step = 2601 (0.332 sec)
INFO:tensorflow:global_step/sec: 432.186
INFO:tensorflow:loss = 25.418535, step = 2701 (0.230 sec)
INFO:tensorflow:global_step/sec: 412.623
INFO:tensorflow:loss = 50.107243, step = 2801 (0.242 sec)
INFO:tensorflow:global_step/sec: 399.47
INFO:tensorflow:loss = 173.75008, step = 2901 (0.249 sec)
INFO:tensorflow:global_step/sec: 353.047
INFO:tensorflow:loss = 57.977493, step = 3001 (0.284 sec)
INFO:tensorflow:global_step/sec: 412.611
INFO:tensorflow:loss = 33.639793, step = 3101 (0.243 sec)
INFO:tensorflow:global_step/sec: 440.477
INFO:tensorflow:loss = 45.355164, step = 3201 (0.226 sec)
INFO:tensorflow:global_step/sec: 152.145
INFO:tensorflow:loss = 166.48463, step = 3301 (0.656 sec)
INFO:tensorflow:global_step/sec: 360.658
INFO:tensorflow:loss = 33.85997, step = 3401 (0.278 sec)
INFO:tensorflow:global_step/sec: 345.302
INFO:tensorflow:loss = 43.66298, step = 3501 (0.290 sec)

INFO:tensorflow:global_step/sec: 357.269
INFO:tensorflow:loss = 92.628365, step = 3601 (0.282 sec)
INFO:tensorflow:global_step/sec: 374.929
INFO:tensorflow:loss = 56.156685, step = 3701 (0.265 sec)
INFO:tensorflow:global_step/sec: 312.715
INFO:tensorflow:loss = 63.190586, step = 3801 (0.319 sec)
INFO:tensorflow:global_step/sec: 372.739
INFO:tensorflow:loss = 128.10101, step = 3901 (0.268 sec)
INFO:tensorflow:global_step/sec: 381.246
INFO:tensorflow:loss = 43.586586, step = 4001 (0.262 sec)
INFO:tensorflow:global_step/sec: 302.91
INFO:tensorflow:loss = 119.95572, step = 4101 (0.328 sec)
INFO:tensorflow:global_step/sec: 276.227
INFO:tensorflow:loss = 61.711555, step = 4201 (0.368 sec)
INFO:tensorflow:global_step/sec: 311.384
INFO:tensorflow:loss = 212.21822, step = 4301 (0.317 sec)
INFO:tensorflow:global_step/sec: 268.29
INFO:tensorflow:loss = 168.77931, step = 4401 (0.375 sec)
INFO:tensorflow:global_step/sec: 177.196
INFO:tensorflow:loss = 106.24856, step = 4501 (0.562 sec)
INFO:tensorflow:global_step/sec: 351.6
INFO:tensorflow:loss = 23.572094, step = 4601 (0.284 sec)
INFO:tensorflow:global_step/sec: 322.66
INFO:tensorflow:loss = 61.37294, step = 4701 (0.310 sec)
INFO:tensorflow:global_step/sec: 338.983
INFO:tensorflow:loss = 105.03748, step = 4801 (0.296 sec)
INFO:tensorflow:global_step/sec: 312.362
INFO:tensorflow:loss = 41.446938, step = 4901 (0.321 sec)
INFO:tensorflow:global_step/sec: 337.586
INFO:tensorflow:loss = 30.895472, step = 5001 (0.296 sec)
INFO:tensorflow:global_step/sec: 301.113
INFO:tensorflow:loss = 113.38377, step = 5101 (0.331 sec)
INFO:tensorflow:global_step/sec: 301.854
INFO:tensorflow:loss = 36.158287, step = 5201 (0.330 sec)
INFO:tensorflow:global_step/sec: 248.261
INFO:tensorflow:loss = 70.95218, step = 5301 (0.403 sec)
INFO:tensorflow:global_step/sec: 330.914
INFO:tensorflow:loss = 191.71407, step = 5401 (0.302 sec)
INFO:tensorflow:global_step/sec: 337.6
INFO:tensorflow:loss = 146.51926, step = 5501 (0.297 sec)
INFO:tensorflow:global_step/sec: 367.146
INFO:tensorflow:loss = 45.72873, step = 5601 (0.273 sec)
INFO:tensorflow:global_step/sec: 286.881
INFO:tensorflow:loss = 66.21464, step = 5701 (0.348 sec)
INFO:tensorflow:global_step/sec: 364.194
INFO:tensorflow:loss = 49.526756, step = 5801 (0.274 sec)
INFO:tensorflow:global_step/sec: 335.928
INFO:tensorflow:loss = 82.97257, step = 5901 (0.299 sec)
INFO:tensorflow:global_step/sec: 327.659
INFO:tensorflow:loss = 31.66983, step = 6001 (0.304 sec)
INFO:tensorflow:global_step/sec: 295.785
INFO:tensorflow:loss = 22.635891, step = 6101 (0.338 sec)
INFO:tensorflow:global_step/sec: 340.077
INFO:tensorflow:loss = 22.913666, step = 6201 (0.294 sec)
INFO:tensorflow:global_step/sec: 348.337
INFO:tensorflow:loss = 30.656403, step = 6301 (0.290 sec)
INFO:tensorflow:global_step/sec: 344.78
INFO:tensorflow:loss = 34.901222, step = 6401 (0.286 sec)
INFO:tensorflow:global_step/sec: 309.468
INFO:tensorflow:loss = 24.955513, step = 6501 (0.324 sec)
INFO:tensorflow:global_step/sec: 327.67
INFO:tensorflow:loss = 41.806572, step = 6601 (0.305 sec)
INFO:tensorflow:global_step/sec: 348.149
INFO:tensorflow:loss = 59.52694, step = 6701 (0.287 sec)
INFO:tensorflow:global_step/sec: 347.018
INFO:tensorflow:loss = 34.696587, step = 6801 (0.289 sec)
INFO:tensorflow:global_step/sec: 306.203
INFO:tensorflow:loss = 35.15828, step = 6901 (0.326 sec)
INFO:tensorflow:global_step/sec: 328.738
INFO:tensorflow:loss = 42.880436, step = 7001 (0.304 sec)
INFO:tensorflow:global_step/sec: 341.053
INFO:tensorflow:loss = 56.530807, step = 7101 (0.292 sec)
INFO:tensorflow:global_step/sec: 334.576
INFO:tensorflow:loss = 38.44307, step = 7201 (0.299 sec)
INFO:tensorflow:global_step/sec: 306.629
INFO:tensorflow:loss = 71.43732, step = 7301 (0.328 sec)
INFO:tensorflow:global_step/sec: 317.241
INFO:tensorflow:loss = 44.989216, step = 7401 (0.316 sec)
INFO:tensorflow:global_step/sec: 317.301
INFO:tensorflow:loss = 26.225328, step = 7501 (0.314 sec)
INFO:tensorflow:global_step/sec: 290.63
INFO:tensorflow:loss = 44.452248, step = 7601 (0.346 sec)
INFO:tensorflow:global_step/sec: 283.104
INFO:tensorflow:loss = 139.98329, step = 7701 (0.353 sec)
INFO:tensorflow:global_step/sec: 354.837
INFO:tensorflow:loss = 22.391422, step = 7801 (0.280 sec)
INFO:tensorflow:global_step/sec: 299.795
INFO:tensorflow:loss = 35.908405, step = 7901 (0.334 sec)
INFO:tensorflow:global_step/sec: 324.496
INFO:tensorflow:loss = 36.081886, step = 8001 (0.311 sec)
INFO:tensorflow:global_step/sec: 287.288
INFO:tensorflow:loss = 95.11684, step = 8101 (0.343 sec)
INFO:tensorflow:global_step/sec: 345.764
INFO:tensorflow:loss = 44.98873, step = 8201 (0.291 sec)
INFO:tensorflow:global_step/sec: 336.458
INFO:tensorflow:loss = 162.95654, step = 8301 (0.297 sec)
INFO:tensorflow:global_step/sec: 318.927
INFO:tensorflow:loss = 30.613003, step = 8401 (0.314 sec)
INFO:tensorflow:global_step/sec: 282.419
INFO:tensorflow:loss = 51.209995, step = 8501 (0.352 sec)
INFO:tensorflow:global_step/sec: 329.847
INFO:tensorflow:loss = 36.70859, step = 8601 (0.305 sec)
INFO:tensorflow:global_step/sec: 310.648
INFO:tensorflow:loss = 25.647652, step = 8701 (0.321 sec)
INFO:tensorflow:global_step/sec: 310.566
INFO:tensorflow:loss = 27.293709, step = 8801 (0.322 sec)
INFO:tensorflow:global_step/sec: 287.166
INFO:tensorflow:loss = 34.036186, step = 8901 (0.350 sec)
INFO:tensorflow:global_step/sec: 312.359
INFO:tensorflow:loss = 21.176441, step = 9001 (0.318 sec)
INFO:tensorflow:global_step/sec: 346.945
INFO:tensorflow:loss = 45.128784, step = 9101 (0.292 sec)
INFO:tensorflow:global_step/sec: 291.027
INFO:tensorflow:loss = 81.842285, step = 9201 (0.343 sec)
INFO:tensorflow:global_step/sec: 347.681
INFO:tensorflow:loss = 32.131397, step = 9301 (0.288 sec)
INFO:tensorflow:global_step/sec: 296.64
INFO:tensorflow:loss = 46.874496, step = 9401 (0.332 sec)
INFO:tensorflow:global_step/sec: 183.227
INFO:tensorflow:loss = 35.37758, step = 9501 (0.550 sec)
INFO:tensorflow:global_step/sec: 307.814
INFO:tensorflow:loss = 91.80283, step = 9601 (0.322 sec)
INFO:tensorflow:global_step/sec: 281.254
INFO:tensorflow:loss = 21.30249, step = 9701 (0.358 sec)
INFO:tensorflow:global_step/sec: 331.993
INFO:tensorflow:loss = 24.39655, step = 9801 (0.301 sec)
INFO:tensorflow:global_step/sec: 278.52
INFO:tensorflow:loss = 34.46844, step = 9901 (0.357 sec)
INFO:tensorflow:Saving checkpoints for 10000 into C:\Users\Hasal\AppData\Local\Temp\tmpheb616br\model.ckpt.
INFO:tensorflow:Loss for final step: 41.219208.

### Evaluation

** Create a prediction input function. Remember to only supprt X_test data and keep shuffle=False. **

In [20]:
pred_fn = tf.estimator.inputs.pandas_input_fn(x=x_test, batch_size=len(x_test), shuffle=False)

** Use model.predict() and pass in your input function. This will produce a generator of predictions, which you can then transform into a list, with list() **

In [21]:
pred_gen = model.predict(input_fn=pred_fn)

** Each item in your list will look like this: **

In [22]:
predictions = list(pred_gen)

INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:Entity <bound method LinearModel.call of <tensorflow.python.feature_column.feature_column_v2.LinearModel object at 0x000002925CB65E08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method LinearModel.call of <tensorflow.python.feature_column.feature_column_v2.LinearModel object at 0x000002925CB65E08>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING: Entity <bound method LinearModel.call of <tensorflow.python.feature_column.feature_column_v2.LinearModel object at 0x000002925CB65E08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method LinearModel.call of <tensorflow.python.feature_column.feature_column_v2.LinearModel object at 0x000002925CB65E08>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method _LinearModelLayer.call of <tensorflow.python.feature_column.feature_column_v2._LinearModelLayer object at 0x000002925CCCE308>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _LinearModelLayer.call of <tensorflow.python.feature_column.feature_column_v2._LinearModelLayer object at 0x000002925CCCE308>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING: Entity <bound method _LinearModelLayer.call of <tensorflow.python.feature_column.feature_column_v2._LinearModelLayer object at 0x000002925CCCE308>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _LinearModelLayer.call of <tensorflow.python.feature_column.feature_column_v2._LinearModelLayer object at 0x000002925CCCE308>>: AssertionError: Bad argument number for Name: 3, expecting 4
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
WARNING:tensorflow:From C:\Users\Hasal\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from C:\Users\Hasal\AppData\Local\Temp\tmpheb616br\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.

** Create a list of only the class_ids key values from the prediction list of dictionaries, these are the predictions you will use to compare against the real y_test values. **

In [23]:
final_preds = [pred['class_ids'][0] for pred in predictions]

In [24]:
final_preds

[0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 ...]

** Import classification_report from sklearn.metrics and then see if you can figure out how to use it to easily get a full report of your model's performance on the test data. **

In [25]:
from sklearn.metrics import classification_report

In [26]:
print(classification_report(y_test, final_preds))

              precision    recall  f1-score   support

           0       0.88      0.91      0.89      7436
           1       0.67      0.61      0.64      2333

   micro avg       0.84      0.84      0.84      9769
   macro avg       0.78      0.76      0.77      9769
weighted avg       0.83      0.84      0.83      9769

# Great Job!